spring.application.name=Fisa OAuth
server.port=9000

# Database Connection
spring.datasource.url=jdbc:mysql://localhost:3306/oauth2_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate Settings
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ???? ?? ?? drop
spring.sql.init.mode=never